apiVersion: v1
kind: ReplicationController
metadata:
  name: fluentd
  labels:
    name: fluentd
spec:
  replicas: 10
  selector:
    name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
      - name: fluentd
        image: registry.docker.yeepay.com:5000/yeepay/fluentd
        volumeMounts:
        - name: docker
          mountPath: "/var/lib/docker/containers"
      volumes:
        - name: docker
          hostPath: 
            path: "/var/lib/docker/containers"
