apiVersion: v1
kind: Pod 
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: registry.docker:5000/busybox
    command:
      - sleep
      - "36000"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
