apiVersion: v1
kind: Pod 
metadata:
  name: ubuntu-echo
  namespace: default
spec:
  containers:
  - image: ubuntu-echo
    imagePullPolicy: IfNotPresent
    name: ubuntu-echo
  restartPolicy: Always
