apiVersion: v1
kind: Service
metadata:
  name: push-ios
  labels:
    name: push-ios
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32702
  type: "NodePort"
  selector:
    name: push-ios
