apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  labels:
    name: kibana
spec:
  replicas: 1
  selector:
    name: kibana
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
      - name: kibana
        image: registry.docker:5000/yeepay/kibana:4.3.1
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "12800Mi"
