apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    name: kibana
spec:
  ports:
    # the port that this service should serve on
  - port: 5600
    targetPort: 5600
    nodePort: 32763
  type: "NodePort"
  selector:
    name: kibana
