apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-type
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "cat", "/etc/config/special.type" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never
