apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached
  labels:
    role: memcached
    type: standalone
spec:
  replicas: 1
  selector:
    role: memcached
    type: standalone
  template:
    metadata:
      labels:
        role: memcached
        type: standalone
    spec:
      containers:
      - name: memcached
        image: "memcached:1.4.24"
        ports:
        - containerPort: 11211
        resources:
          limits:
            cpu: "2"
            memory: "4096M"
