apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    role: mysql-standalone
spec:
  replicas: 1
  selector:
    role: mysql-standalone
  template:
    metadata:
      labels:
        role: mysql-standalone
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: storage
      volumes:
      - name: storage
        rbd: 
          monitors:
            - "10.149.149.2:6789"
            - "10.149.149.3:6789"
            - "10.149.149.4:6789"
          pool: rbd
          image: mysql
          secretRef:
            name: ceph-secret
          fsType: ext4
          readOnly: false
