apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    role: mysql-standalone
spec:
  selector:
    role: mysql-standalone
  type: NodePort
  ports:
  - name: http
    port: 3306
    protocol: TCP
    nodePort: 32306
