apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    role: mysql-standalone
spec:
  replicas: 1
  selector:
    role: mysql-standalone
  template:
    metadata:
      labels:
        role: mysql-standalone
    spec:
      containers:
      - name: mysql
        image: registry.docker:5000/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
