apiVersion: v1
kind: ReplicationController
metadata:
  name: donate
  labels:
    name: donate
spec:
  replicas: 2
  selector:
    name: donate
  template:
    metadata:
      labels:
        name: donate
    spec:
      containers:
      - name: donate
        image: registry.docker.yeepay.com:5000/yeepay/donate:v1.0.0
        ports:
        - containerPort: 8080
