apiVersion: v1
kind: Service
metadata:
  name: donate
  labels:
    name: donate
spec:
  ports:
    # the port that this service should serve on
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 32764
  type: "NodePort"
  selector:
    name: donate
