apiVersion: v1
kind: Service
metadata:
  name: gongyi
  labels:
    name: gongyi
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32765
  type: "NodePort"
  selector:
    name: gongyi
