apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  labels:
    type: rabbitmq
    role: mq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: rabbitmq
        role: mq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.0
        ports:
        - containerPort: 5672
