apiVersion: v1
kind: ReplicationController
metadata:
  name: push-android-2
  labels:
    name: push-android-2
spec:
  replicas: 1
  selector:
    name: push-android-2
    role: android
  template:
    metadata:
      labels:
        name: push-android-2
        role: android
    spec:
      containers:
      - name: push-android
        image: registry.docker:5000/push-android:v1
        ports:
        - containerPort: 8080
        - containerPort: 8000
        resources:
          limits:
            cpu: "4"
            memory: "8092Mi"
        livenessProbe:
          httpGet:
            path: /android-pns/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
        volumeMounts:
        - mountPath: /apps/log
          name: storage
      volumes:
      - name: storage 
        rbd: 
          monitors:
            - "10.149.149.1:6789"
          pool: rbd
          image: push-android-2
          secretRef:
            name: ceph-secret
          fsType: ext4
          readOnly: false
