apiVersion: v1
kind: ReplicationController
metadata:
  name: yeepay-site
  labels:
    name: yeepay-site
spec:
  replicas: 2
  selector:
    name: yeepay-site
  template:
    metadata:
      labels:
        name: yeepay-site
    spec:
      containers:
      - name: yeepay-site
        image: registry.docker.yeepay.com:5000/yeepay/yeepay-site:v1.0.0
        ports:
        - containerPort: 8080
