apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: yeepay/mongodb:3.0
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
            - name: mongo-master-nfs
              mountPath: "/data/db"
      volumes:
        - name: mongo-master-nfs
          nfs:
            server: 172.17.0.30
            path: "/tmp"
