apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-slave2
  labels:
    name: mongo-slave
spec:
  replicas: 1
  selector:
    name: mongo-slave2
  template:
    metadata:
      labels:
        name: mongo-slave2
    spec:
      containers:
      - name: slave2
        image: mongo
        command:
          - mongod
          - "--slave"
          - "--source"
          - mongo-master 
          - "--smallfiles"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: nfs-mongo-slave2
          mountPath: "/data/db"
      volumes:
      - name: nfs-mongo-slave2
        server: 172.17.0.4
        path: "/tmp"
