apiVersion: v1
kind: ReplicationController
metadata:
  name: yeepay-boss
  labels:
    name: yeepay-boss
spec:
  replicas: 2
  selector:
    name: yeepay-boss
  template:
    metadata:
      labels:
        name: yeepay-boss
    spec:
      containers:
      - name: yeepay-boss
        image: yeepay/yeepay-boss
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nfs-yeepay-boss
          mountPath: "/usr/local/yeepay-boss/public"
      volumes:
        - name: nfs-yeepay-boss
          server: 172.17.0.19
          path: "/tmp"
