apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    role: postgres-standalone
spec:
  selector:
    role: postgres-standalone
  ports:
  - name: http
    port: 5432
    protocol: TCP
