apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-master
  labels:
    name: mongo-master
spec:
  replicas: 1
  selector:
    name: mongo-master
  template:
    metadata:
      labels:
        name: mongo-master
    spec:
      containers:
      - name: master
        image: mongo
        command:
          - mongod
          - "--master"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-master
          mountPath: "/data/db"
      volumes:
        - name: mongo-master
          emptyDir: {}
