apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-slave
  labels:
    name: mongo-slave
spec:
  replicas: 2
  selector:
    name: mongo-slave
  template:
    metadata:
      labels:
        name: mongo-slave
    spec:
      containers:
      - name: slave
        image: mongo
        command:
          - mongod
          - "--slave"
          - "--source"
          - mongo-master 
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-slave
          mountPath: "/data/db"
      volumes:
        - name: mongo-slave
          emptyDir: {}
