apiVersion: v1
kind: ReplicationController
metadata:
  name: fluentd-writer
  labels:
    name: fluentd-writer
spec:
  replicas: 1
  selector:
    name: fluentd-writer
  template:
    metadata:
      labels:
        name: fluentd-writer
    spec:
      containers:
      - name: fluentd-writer
        image: registry.docker.yeepay.com:5000/yeepay/fluentd-writer
        volumeMounts:
        - name: docker
          mountPath: "/var/lib/docker/containers"
      volumes:
        - name: docker
          hostPath: 
            path: "/var/lib/docker/containers"
