apiVersion: v1
kind: Service
metadata:
  name: yeepay-img
  labels:
    name: yeepay-img
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: yeepay-img
