apiVersion: v1
kind: ReplicationController
metadata:
  name: yeepay-img
  labels:
    name: yeepay-img
spec:
  replicas: 2
  selector:
    name: yeepay-img
  template:
    metadata:
      labels:
        name: yeepay-img
    spec:
      containers:
      - name: yeepay-img 
        image: registry.docker.yeepay.com:5000/yeepay/img-server
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nfs-yeepay-img
          mountPath: "/usr/local/yeepay-img/public/"
      volumes:
        - name: nfs-yeepay-img
          server: 172.23.86.22
          path: "/tmp"
