apiVersion: v1
kind: Service
metadata:
  name: redis-master-memory
  labels:
    name: redis-master-memory
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-master-memory
